import {
  // Alert,
  // AlertProps,
  Anchor,
  AnchorProps,
  Blockquote,
  BlockquoteProps,
  Divider,
  DividerProps,
  Highlight,
  HighlightProps,
  // Image,
  List,
  ListItem,
  ListItemProps,
  ListProps,
  Mark,
  MarkProps,
  Text,
  TextProps,
  Title,
  TitleProps,
} from "@mantine/core";
import { MDXComponents } from "next-mdx-remote-client/rsc";
import { CodeBlock } from "./code-block";
// import NextImage, { ImageProps } from "next/image";

export const components: MDXComponents = {
  a: (props: AnchorProps) => <Anchor {...props} />,
  hr: (props: DividerProps) => <Divider {...props} />,
  p: (props: TextProps) => <Text {...props} />,
  h1: (props: TitleProps) => <Title order={1} {...props} />,
  h2: (props: TitleProps) => <Title order={2} {...props} />,
  h3: (props: TitleProps) => <Title order={3} {...props} />,
  h4: (props: TitleProps) => <Title order={4} {...props} />,
  h5: (props: TitleProps) => <Title order={5} {...props} />,
  h6: (props: TitleProps) => <Title order={6} {...props} />,
  pre: (props) => <div {...props} />,
  code: CodeBlock,
  blockquote: (props: BlockquoteProps) => <Blockquote {...props} />,
  highlight: (props: HighlightProps) => <Highlight {...props} />,
  mark: (props: MarkProps) => <Mark {...props} />,
  ol: (props: ListProps) => <List type="ordered" center {...props} />,
  ul: (props: ListProps) => <List center {...props} />,
  li: (props: ListItemProps) => <ListItem {...props} />,
  // alert: (props: AlertProps) => <Alert {...props} />,
  // img: (props: ImageProps) => <Image component={NextImage} {...props} />,
};
