import {
  Alert,
  Anchor,
  AnchorProps,
  Blockquote,
  BlockquoteProps,
  Divider,
  DividerProps,
  Highlight,
  HighlightProps,
  ListItem,
  ListItemProps,
  ListProps,
  Mark,
  MarkProps,
  Table,
  TableProps,
  TableTbody,
  TableTbodyProps,
  TableTd,
  TableTdProps,
  TableTh,
  TableThead,
  TableTheadProps,
  TableThProps,
  TableTr,
  TableTrProps,
  Text,
  TextProps,
  Title,
  TitleProps,
} from "@mantine/core";
import { MDXComponents } from "next-mdx-remote-client/rsc";
import { CodeBlock } from "./code-block";
import { List } from "./list";
import { ComponentProps } from "react";

export const components: MDXComponents = {
  a: (p: AnchorProps) => <Anchor {...p} />,
  hr: (p: DividerProps) => <Divider {...p} />,
  p: (p: TextProps) => <Text {...p} />,
  h1: (p: TitleProps) => <Title order={1} {...p} />,
  h2: (p: TitleProps) => <Title order={2} {...p} />,
  h3: (p: TitleProps) => <Title order={3} {...p} />,
  h4: (p: TitleProps) => <Title order={4} {...p} />,
  h5: (p: TitleProps) => <Title order={5} {...p} />,
  h6: (p: TitleProps) => <Title order={6} {...p} />,
  pre: (p: ComponentProps<"div">) => <div {...p} />,
  code: CodeBlock,
  blockquote: (p: BlockquoteProps) => <Blockquote {...p} />,
  highlight: (p: HighlightProps) => <Highlight {...p} />,
  mark: (p: MarkProps) => <Mark {...p} />,
  ol: (p: ListProps) => <List type="ordered" {...p} />,
  ul: (p: ListProps) => <List {...p} />,
  li: (p: ListItemProps) => <ListItem {...p} />,
  table: (p: TableProps) => <Table withTableBorder withColumnBorders {...p} />,
  thead: (p: TableTheadProps) => <TableThead {...p} />,
  tbody: (p: TableTbodyProps) => <TableTbody {...p} />,
  tr: (p: TableTrProps) => <TableTr {...p} />,
  th: (p: TableThProps) => <TableTh {...p} />,
  td: (p: TableTdProps) => <TableTd {...p} />,
  // custom components
  Alert,
};
